version: '3'
# https://linoxide.com/containers/setup-lemp-stack-docker/
# http://www.inanzzz.com/index.php/post/zpbw/creating-a-simple-php-fpm-nginx-and-mysql-application-with-docker-compose
#https://www.pascallandau.com/blog/php-php-fpm-and-nginx-on-docker-in-windows-10/
#http://www.inanzzz.com/index.php/post/0e95/copying-symfony-application-into-docker-container-with-multi-stage-builds
#https://learn2torials.com/a/dockerize-reactjs-app
#https://knplabs.com/en/blog/how-to-dockerise-a-symfony-4-project
#https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx-server/logs:/var/log/nginx
      - ./nginx-server/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/srv/www
    depends_on:
      - phpfpm

  phpfpm:
    build:
      context: .
      dockerfile: docker/phpfpm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./www:/srv/www
      - ./docker/phpfpm/default.conf:/usr/local/etc/php-fpm.d/default.conf
    environment:
      MYSQL_USER: "dummy"
      MYSQL_PASSWORD: "dummy"

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    depends_on:
      - phpfpm
    environment:
      MYSQL_ROOT_PASSWORD: "dummy"
      MYSQL_DATABASE: "dummy"
      MYSQL_USER: "dummy"
      MYSQL_PASSWORD: "dummy"
    volumes:
      - my-db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      - NODE_ENV=test
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./app:/app

volumes:
  my-db: